/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.pro.software.academicosexta;

/**
 *
 * @author Andreia
 */
public class MostraAlunosCursoTela extends javax.swing.JFrame {

    /**
     * Creates new form alunosCursoFrame
     */
    public MostraAlunosCursoTela(Curso curso) {
        super("Alunos por Curso");
        initComponents();
        idCursoLabel.setText(Integer.toString(curso.getId()));
        nomeCursoLabel.setText(curso.getNome());
        tipoCursoLabel.setText(curso.getTipo());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alunosCursoPanel = new javax.swing.JPanel();
        idCursoLabel = new javax.swing.JLabel();
        nomeCursoLabel = new javax.swing.JLabel();
        tipoCursoLabel = new javax.swing.JLabel();
        voltarAlunosCursoButtom = new javax.swing.JButton();
        sairAlunosCursoButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idCursoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("id curso"));

        nomeCursoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("nome curso"));

        tipoCursoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("tipo curso"));

        voltarAlunosCursoButtom.setText("Voltar");
        voltarAlunosCursoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAlunosCursoButtomActionPerformed(evt);
            }
        });

        sairAlunosCursoButtom.setText("Sair");
        sairAlunosCursoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairAlunosCursoButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunosCursoPanelLayout = new javax.swing.GroupLayout(alunosCursoPanel);
        alunosCursoPanel.setLayout(alunosCursoPanelLayout);
        alunosCursoPanelLayout.setHorizontalGroup(
            alunosCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunosCursoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(idCursoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(nomeCursoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(tipoCursoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(alunosCursoPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(voltarAlunosCursoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairAlunosCursoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        alunosCursoPanelLayout.setVerticalGroup(
            alunosCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunosCursoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(alunosCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipoCursoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(nomeCursoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idCursoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addGroup(alunosCursoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltarAlunosCursoButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(sairAlunosCursoButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(alunosCursoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(alunosCursoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairAlunosCursoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairAlunosCursoButtomActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairAlunosCursoButtomActionPerformed

    private void voltarAlunosCursoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAlunosCursoButtomActionPerformed
        CursosTela ct = new CursosTela();
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarAlunosCursoButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostraAlunosCursoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostraAlunosCursoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostraAlunosCursoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostraAlunosCursoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MostraAlunosCursoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alunosCursoPanel;
    private javax.swing.JLabel idCursoLabel;
    private javax.swing.JLabel nomeCursoLabel;
    private javax.swing.JButton sairAlunosCursoButtom;
    private javax.swing.JLabel tipoCursoLabel;
    private javax.swing.JButton voltarAlunosCursoButtom;
    // End of variables declaration//GEN-END:variables
}
